services:
  db:
    hostname: db
    image: postgis/postgis:17-3.5
    shm_size: 512m
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    restart: "unless-stopped"
    networks:
      - demo-qgis-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "${DB_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/11_init_db.sh
      - ./init_db.sql:/sql/init_db.sql
    command: [ "postgres", "-c", "log_statement=mod", "-c", "log_min_messages=INFO" ]

  qgis:
    image: "camptocamp/qgis-server:latest"
    hostname: "qgisserver-c2c"
    environment:
      PGSERVICEFILE: "/io/pg_service.conf"
      QGIS_PROJECT_FILE: "/etc/qgisserver/foo/server.qgs"
      QGIS_SERVER_LOG_LEVEL: 0
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES: "/etc/qgisserver/foo"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - demo-qgis-net
    volumes:
      - ./data:/etc/qgisserver
      - ./conf:/io/
    ports:
      - "8089:80" 
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata: {}

networks:
  demo-qgis-net:
    name: demo-qgis-net
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
          ip_range: 172.32.5.0/24
          gateway: 172.32.0.1
